# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  -
    main: cmd/main.go
    binary: ladder
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
        - goos: windows
          format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: 'foo'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^public:'
      - '^.github:'

project_name: your_project_name

release:
  github:
    owner: your-github-username
    name: your-repo-name

brews:
  - name: your_project_name
    homepage: "https://github.com/your_github_username/your_project_name"
    description: "A brief description of your project"
    test: |
      system "#{bin}/your_project_name --version"
    install: |
      bin.install "your_project_name"
    dependencies:
      - go
    tap:
      owner: your-github-username
      name: homebrew-tap
      token: "{{ .Env.GORELEASER_GITHUB_TOKEN }}"

name: Release Binaries

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  release:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest

      - name: Run GoReleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
        with:
          args: release --clean
