project_name: my_project
---
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: build
    main: ./cmd/main.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    files:
      - LICENSE
      - README.md

release:
  github:
    owner: your-github-username
    name: your-repo-name
    # token: ${{ secrets.GORELEASER_GITHUB_TOKEN }}