project_name: my_project

release:
  github:
    owner: my_github_username
    name: my_project

builds:
  - main: ./cmd/my_project
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64