
# This file should contain GoReleaser configuration, not GitHub Actions workflow.
# Move the jobs section to a .github/workflows/ file and keep GoReleaser configuration here.
# Example GoReleaser configuration:
project_name: my_project
release:
  github:
    owner: my_github_username
    name: my_project
builds:
  - main: ./cmd/my_project
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64