---
# This GitHub Actions workflow is named "Release Binaries".
# It is designed to automate the process of releasing binaries for the project.
# The workflow is defined in the file located at:
# /Users/andrewbulthuis/VS Code/ladder/.github/workflows/release-binaries.yaml
name: Release Binaries

on:
  push:
    #branches:
    #  - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
  workflow_dispatch:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Set version
        run: |
          echo -n $(git describe --tags --abbrev=0) > handlers/VERSION
      -
        name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GORELEASER }}
# GORELEASER_GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}