name: Release Binaries

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install npm dependencies
        run: npm install

      - name: Install pnpx
        run: npm install -g pnpm

      - name: Build JavaScript project
        run: npm run build

      - name: Set up C++ environment
        run: sudo apt-get install -y build-essential

      - name: Build C++ project
        run: make

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}